# Generated by Django 3.2.5 on 2021-07-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_short_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('age', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('teacher_img', models.ImageField(upload_to='media/teacher_img')),
                ('teacher_class', models.ManyToManyField(to='teacher.TeacherClass')),
                ('teacher_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherdepartment')),
            ],
        ),
    ]
