# Generated by Django 3.2.5 on 2021-07-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_short_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('student_number', models.CharField(max_length=12)),
                ('student_img', models.ImageField(upload_to='media/student_img')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclassinfo')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentsectioninfo')),
            ],
        ),
    ]
